### ISSUE TITLE
When i enable the journal layer "bullets" stop working

### ISSUE THREAD

**Issue by hhagblom** [borgnix/spacemacs-journal#6]
When I enable the journal layer the nice bullets stop working in org mode, when I remove the layer they come back. I checked the messages buffer for some leads but found nothing that stands out.

Please let me know if you need anything to troubleshoot the issue.

**Comment by ruibinx** [comment]
Following procedures may help:

- Check if your spacemacs, org-mode, org-journal package are installed properly. Update them to the latest version.

- Backup your spacemacs configs and fresh install the spacemacs-journal layer again(with no other unrelated packages and configs).

If the problem persists, please provide the version of your spacemacs, org-journal, org-mode, detailed explanation of what the bug is(better with screenshots), steps to reproduce the bug. 

By the way, I recommend you opening an issue at [org-journal](https://github.com/bastibe/org-journal) since it's most likely a bug from upstream.
